spring.application.name=api-agendamento

# ===============================
# H2 DATABASE
# ===============================
spring.datasource.url=jdbc:h2:mem:agendamento-db
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# H2 CONSOLE
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# LOGGING
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE