# src/main/resources/graphql/schema.graphqls
type Historico {
    id: ID!
    pacienteId: String!
    profissionalId: String!
    dataHora: String!
    descricao: String
}

type Query {
    historico(id: ID!): Historico
    historicos: [Historico!]!
    historicosPorPaciente(pacienteId: String!): [Historico!]!
    historicosPorProfissional(profissionalId: String!): [Historico!]!
    historicosPorPeriodo(inicio: String!, fim: String!): [Historico!]!
}

type Mutation {
    criarHistorico(pacienteId: String!, profissionalId: String!, descricao: String, dataHora: String): Historico!
    deletarHistorico(id: ID!): Boolean!
}