spring.application.name=notificacao

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Jackson Config for LocalDateTime
spring.jackson.serialization.write-dates-as-timestamps=false
